/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

/**
 *
 * @author MatheusAntônio
 */
public class Prototipo_CarrinhoDeCompras extends javax.swing.JFrame {

    /**
     * Creates new form Prototipo_CarrinhoDeCompras
     */
    public Prototipo_CarrinhoDeCompras() {
        initComponents();

        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBackground = new javax.swing.JPanel();
        pnlCarrinho = new javax.swing.JPanel();
        tbmCarrinho = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtCEP = new javax.swing.JTextField();
        lblCEP = new javax.swing.JLabel();
        lblFrete = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        btnComprar2 = new javax.swing.JButton();
        lblPreco1 = new javax.swing.JLabel();
        lblPreco2 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        MenuCadastro = new javax.swing.JMenu();
        cadastroCLiente = new javax.swing.JMenuItem();
        cadastroFuncionario = new javax.swing.JMenuItem();
        MenuManutencao = new javax.swing.JMenu();
        gerenciarCliente = new javax.swing.JMenuItem();
        gerenciarFuncionario = new javax.swing.JMenuItem();
        MenuAreaVenda = new javax.swing.JMenu();
        Produtos = new javax.swing.JMenuItem();
        Carrinho = new javax.swing.JMenuItem();
        MenuLog = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        MenuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Carrinho de Compras");

        pnlBackground.setBackground(new java.awt.Color(255, 255, 255));

        pnlCarrinho.setBackground(new java.awt.Color(255, 255, 255));
        pnlCarrinho.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Carrinho de Compras", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Imagem", "Produto", "Descrição", "Quantidade", "Valor"
            }
        ));
        tbmCarrinho.setViewportView(jTable1);

        lblCEP.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCEP.setText("CEP:");

        lblFrete.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblFrete.setText("Frete:");

        lblTotal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblTotal.setText("Total:");

        btnComprar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/next.png"))); // NOI18N
        btnComprar2.setText("COMPRAR");

        lblPreco1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPreco1.setText("R$ 0,00");

        lblPreco2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPreco2.setText("R$ 0,00");

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/back.png"))); // NOI18N
        btnCancelar.setText("VOLTAR");

        javax.swing.GroupLayout pnlCarrinhoLayout = new javax.swing.GroupLayout(pnlCarrinho);
        pnlCarrinho.setLayout(pnlCarrinhoLayout);
        pnlCarrinhoLayout.setHorizontalGroup(
            pnlCarrinhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCarrinhoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCarrinhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tbmCarrinho)
                    .addGroup(pnlCarrinhoLayout.createSequentialGroup()
                        .addGroup(pnlCarrinhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTotal)
                            .addGroup(pnlCarrinhoLayout.createSequentialGroup()
                                .addComponent(lblCEP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(190, 190, 190)
                                .addComponent(lblFrete)))
                        .addGap(18, 18, 18)
                        .addGroup(pnlCarrinhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPreco1)
                            .addComponent(lblPreco2))
                        .addGap(0, 161, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCarrinhoLayout.createSequentialGroup()
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnComprar2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlCarrinhoLayout.setVerticalGroup(
            pnlCarrinhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCarrinhoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tbmCarrinho, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(pnlCarrinhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCEP)
                    .addComponent(txtCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFrete)
                    .addComponent(lblPreco1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCarrinhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotal)
                    .addComponent(lblPreco2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(pnlCarrinhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnComprar2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlBackgroundLayout = new javax.swing.GroupLayout(pnlBackground);
        pnlBackground.setLayout(pnlBackgroundLayout);
        pnlBackgroundLayout.setHorizontalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlCarrinho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlBackgroundLayout.setVerticalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlCarrinho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        MenuCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/new.png"))); // NOI18N
        MenuCadastro.setText("Cadastro");

        cadastroCLiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cliente.png"))); // NOI18N
        cadastroCLiente.setText("Cadastro de Cliente");
        MenuCadastro.add(cadastroCLiente);

        cadastroFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/funcionario.png"))); // NOI18N
        cadastroFuncionario.setText("Cadastro de Funcionario");
        MenuCadastro.add(cadastroFuncionario);

        menuBar.add(MenuCadastro);

        MenuManutencao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/settings.png"))); // NOI18N
        MenuManutencao.setText("Manutenção");

        gerenciarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/alterclient.png"))); // NOI18N
        gerenciarCliente.setText("Gerenciar Clientes");
        gerenciarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerenciarClienteActionPerformed(evt);
            }
        });
        MenuManutencao.add(gerenciarCliente);

        gerenciarFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/funcionario.png"))); // NOI18N
        gerenciarFuncionario.setText("Gerenciar Funcionários");
        MenuManutencao.add(gerenciarFuncionario);

        menuBar.add(MenuManutencao);

        MenuAreaVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/sale.png"))); // NOI18N
        MenuAreaVenda.setText("Área de Vendas");

        Produtos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/bag.png"))); // NOI18N
        Produtos.setText("Produtos");
        MenuAreaVenda.add(Produtos);

        Carrinho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/buy.png"))); // NOI18N
        Carrinho.setText("Carrinho de Compras");
        MenuAreaVenda.add(Carrinho);

        menuBar.add(MenuAreaVenda);

        MenuLog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/log.png"))); // NOI18N
        MenuLog.setText("Relatório");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/logsintetic.png"))); // NOI18N
        jMenuItem1.setText("Relatório Sintético");
        MenuLog.add(jMenuItem1);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/lolanalitic.png"))); // NOI18N
        jMenuItem2.setText("Relatório Analítico");
        MenuLog.add(jMenuItem2);

        menuBar.add(MenuLog);

        MenuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/out.png"))); // NOI18N
        MenuSair.setText("Sair");
        menuBar.add(MenuSair);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gerenciarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerenciarClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gerenciarClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Prototipo_CarrinhoDeCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Prototipo_CarrinhoDeCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Prototipo_CarrinhoDeCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Prototipo_CarrinhoDeCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Prototipo_CarrinhoDeCompras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Carrinho;
    private javax.swing.JMenu MenuAreaVenda;
    private javax.swing.JMenu MenuCadastro;
    private javax.swing.JMenu MenuLog;
    private javax.swing.JMenu MenuManutencao;
    private javax.swing.JMenu MenuSair;
    private javax.swing.JMenuItem Produtos;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnComprar2;
    private javax.swing.JMenuItem cadastroCLiente;
    private javax.swing.JMenuItem cadastroFuncionario;
    private javax.swing.JMenuItem gerenciarCliente;
    private javax.swing.JMenuItem gerenciarFuncionario;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblCEP;
    private javax.swing.JLabel lblFrete;
    private javax.swing.JLabel lblPreco1;
    private javax.swing.JLabel lblPreco2;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JPanel pnlBackground;
    private javax.swing.JPanel pnlCarrinho;
    private javax.swing.JScrollPane tbmCarrinho;
    private javax.swing.JTextField txtCEP;
    // End of variables declaration//GEN-END:variables
}
