/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

/**
 *
 * @author MatheusAntônio
 */
public class Prototipo_TelaVenda extends javax.swing.JFrame {

    /**
     * Creates new form Prototipo_TelaVenda
     */
    public Prototipo_TelaVenda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar = new javax.swing.JMenuBar();
        MenuCadastro = new javax.swing.JMenu();
        cadastroCLiente = new javax.swing.JMenuItem();
        cadastroFuncionario = new javax.swing.JMenuItem();
        MenuManutencao = new javax.swing.JMenu();
        gerenciarCliente = new javax.swing.JMenuItem();
        gerenciarFuncionario = new javax.swing.JMenuItem();
        MenuAreaVenda = new javax.swing.JMenu();
        Produtos = new javax.swing.JMenuItem();
        Carrinho = new javax.swing.JMenuItem();
        MenuLog = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        MenuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MenuCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/new.png"))); // NOI18N
        MenuCadastro.setText("Cadastro");

        cadastroCLiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cliente.png"))); // NOI18N
        cadastroCLiente.setText("Cadastro de Cliente");
        MenuCadastro.add(cadastroCLiente);

        cadastroFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/funcionario.png"))); // NOI18N
        cadastroFuncionario.setText("Cadastro de Funcionario");
        MenuCadastro.add(cadastroFuncionario);

        menuBar.add(MenuCadastro);

        MenuManutencao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/settings.png"))); // NOI18N
        MenuManutencao.setText("Manutenção");

        gerenciarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/alterclient.png"))); // NOI18N
        gerenciarCliente.setText("Gerenciar Clientes");
        gerenciarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerenciarClienteActionPerformed(evt);
            }
        });
        MenuManutencao.add(gerenciarCliente);

        gerenciarFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/funcionario.png"))); // NOI18N
        gerenciarFuncionario.setText("Gerenciar Funcionários");
        MenuManutencao.add(gerenciarFuncionario);

        menuBar.add(MenuManutencao);

        MenuAreaVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/sale.png"))); // NOI18N
        MenuAreaVenda.setText("Área de Vendas");

        Produtos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/bag.png"))); // NOI18N
        Produtos.setText("Produtos");
        MenuAreaVenda.add(Produtos);

        Carrinho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/buy.png"))); // NOI18N
        Carrinho.setText("Carrinho de Compras");
        MenuAreaVenda.add(Carrinho);

        menuBar.add(MenuAreaVenda);

        MenuLog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/log.png"))); // NOI18N
        MenuLog.setText("Relatório");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/logsintetic.png"))); // NOI18N
        jMenuItem1.setText("Relatório Sintético");
        MenuLog.add(jMenuItem1);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/lolanalitic.png"))); // NOI18N
        jMenuItem2.setText("Relatório Analítico");
        MenuLog.add(jMenuItem2);

        menuBar.add(MenuLog);

        MenuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/out.png"))); // NOI18N
        MenuSair.setText("Sair");
        menuBar.add(MenuSair);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 513, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 423, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gerenciarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerenciarClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gerenciarClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Prototipo_TelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Prototipo_TelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Prototipo_TelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Prototipo_TelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Prototipo_TelaVenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Carrinho;
    private javax.swing.JMenu MenuAreaVenda;
    private javax.swing.JMenu MenuCadastro;
    private javax.swing.JMenu MenuLog;
    private javax.swing.JMenu MenuManutencao;
    private javax.swing.JMenu MenuSair;
    private javax.swing.JMenuItem Produtos;
    private javax.swing.JMenuItem cadastroCLiente;
    private javax.swing.JMenuItem cadastroFuncionario;
    private javax.swing.JMenuItem gerenciarCliente;
    private javax.swing.JMenuItem gerenciarFuncionario;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables
}
