/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

/**
 *
 * @author MatheusAntônio
 */
public class Venda_Forma_Pagamento_View extends javax.swing.JFrame {

    /**
     * Creates new form Pagamento
     */
    public Venda_Forma_Pagamento_View() {
        initComponents();

        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gpbFormaPagamento = new javax.swing.ButtonGroup();
        gpbBandeira = new javax.swing.ButtonGroup();
        pnlBackground = new javax.swing.JPanel();
        pnlBotao = new javax.swing.JPanel();
        btnComprar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        pnlFormaPagamento = new javax.swing.JPanel();
        rdbDebito = new javax.swing.JRadioButton();
        rdbBoleto = new javax.swing.JRadioButton();
        rdbCredito = new javax.swing.JRadioButton();
        pnlDadosCartao = new javax.swing.JPanel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        lblNomeCartao = new javax.swing.JLabel();
        mskCVV = new javax.swing.JFormattedTextField();
        txtNomeCartao = new javax.swing.JTextField();
        lblCVV = new javax.swing.JLabel();
        lblDataValidade = new javax.swing.JLabel();
        lblNumeroCartao = new javax.swing.JLabel();
        mskNumeroCartao = new javax.swing.JFormattedTextField();
        rdbMastercard = new javax.swing.JRadioButton();
        rdbElo = new javax.swing.JRadioButton();
        rdbVisa = new javax.swing.JRadioButton();
        lblBandeira = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        MenuCadastro = new javax.swing.JMenu();
        cadastroCLiente = new javax.swing.JMenuItem();
        cadastroFuncionario = new javax.swing.JMenuItem();
        MenuManutencao = new javax.swing.JMenu();
        gerenciarCliente = new javax.swing.JMenuItem();
        gerenciarFuncionario = new javax.swing.JMenuItem();
        MenuAreaVenda = new javax.swing.JMenu();
        Produtos = new javax.swing.JMenuItem();
        Carrinho = new javax.swing.JMenuItem();
        MenuLog = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        MenuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pagamento");

        pnlBackground.setBackground(new java.awt.Color(255, 255, 255));

        pnlBotao.setBackground(new java.awt.Color(255, 255, 255));

        btnComprar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/next.png"))); // NOI18N
        btnComprar.setText("COMPRAR");

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/back.png"))); // NOI18N
        btnCancelar.setText("VOLTAR");

        javax.swing.GroupLayout pnlBotaoLayout = new javax.swing.GroupLayout(pnlBotao);
        pnlBotao.setLayout(pnlBotaoLayout);
        pnlBotaoLayout.setHorizontalGroup(
            pnlBotaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122)
                .addComponent(btnComprar, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlBotaoLayout.setVerticalGroup(
            pnlBotaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBotaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnComprar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pnlFormaPagamento.setBackground(new java.awt.Color(255, 255, 255));
        pnlFormaPagamento.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Forma de Pagamento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        gpbFormaPagamento.add(rdbDebito);
        rdbDebito.setText("Cartão de Débito");

        gpbFormaPagamento.add(rdbBoleto);
        rdbBoleto.setText("Boleto Cancário");

        gpbFormaPagamento.add(rdbCredito);
        rdbCredito.setText("Cartão de Crédito");

        javax.swing.GroupLayout pnlFormaPagamentoLayout = new javax.swing.GroupLayout(pnlFormaPagamento);
        pnlFormaPagamento.setLayout(pnlFormaPagamentoLayout);
        pnlFormaPagamentoLayout.setHorizontalGroup(
            pnlFormaPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFormaPagamentoLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(rdbCredito)
                .addGap(101, 101, 101)
                .addComponent(rdbDebito)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rdbBoleto)
                .addGap(50, 50, 50))
        );
        pnlFormaPagamentoLayout.setVerticalGroup(
            pnlFormaPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFormaPagamentoLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(pnlFormaPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbCredito)
                    .addComponent(rdbDebito)
                    .addComponent(rdbBoleto))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pnlDadosCartao.setBackground(new java.awt.Color(255, 255, 255));
        pnlDadosCartao.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados do Cartão", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        try {
            jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lblNomeCartao.setText("Nome do Cartão:");

        try {
            mskCVV.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        txtNomeCartao.setText(" ");

        lblCVV.setText("CVV:");

        lblDataValidade.setText("Data de Validade:");

        lblNumeroCartao.setText("Número do Cartão:");

        try {
            mskNumeroCartao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#### #### #### ####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        gpbBandeira.add(rdbMastercard);
        rdbMastercard.setText("MasterCard");

        gpbBandeira.add(rdbElo);
        rdbElo.setText("Elo");

        gpbBandeira.add(rdbVisa);
        rdbVisa.setText("Visa");

        lblBandeira.setText("Bandeira:");

        javax.swing.GroupLayout pnlDadosCartaoLayout = new javax.swing.GroupLayout(pnlDadosCartao);
        pnlDadosCartao.setLayout(pnlDadosCartaoLayout);
        pnlDadosCartaoLayout.setHorizontalGroup(
            pnlDadosCartaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDadosCartaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDadosCartaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblNomeCartao)
                    .addComponent(lblNumeroCartao)
                    .addComponent(lblBandeira))
                .addGap(18, 18, 18)
                .addGroup(pnlDadosCartaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDadosCartaoLayout.createSequentialGroup()
                        .addComponent(rdbMastercard)
                        .addGap(18, 18, 18)
                        .addComponent(rdbVisa)
                        .addGap(18, 18, 18)
                        .addComponent(rdbElo)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtNomeCartao)
                    .addGroup(pnlDadosCartaoLayout.createSequentialGroup()
                        .addComponent(mskNumeroCartao, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(lblCVV)
                        .addGap(18, 18, 18)
                        .addComponent(mskCVV, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblDataValidade)
                        .addGap(18, 18, 18)
                        .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlDadosCartaoLayout.setVerticalGroup(
            pnlDadosCartaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDadosCartaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDadosCartaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeCartao)
                    .addComponent(txtNomeCartao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(pnlDadosCartaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumeroCartao)
                    .addComponent(mskNumeroCartao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCVV)
                    .addComponent(mskCVV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDataValidade)
                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(pnlDadosCartaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbMastercard)
                    .addComponent(rdbElo)
                    .addComponent(rdbVisa)
                    .addComponent(lblBandeira))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout pnlBackgroundLayout = new javax.swing.GroupLayout(pnlBackground);
        pnlBackground.setLayout(pnlBackgroundLayout);
        pnlBackgroundLayout.setHorizontalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBackgroundLayout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(pnlBotao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlBackgroundLayout.createSequentialGroup()
                        .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlFormaPagamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlDadosCartao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        pnlBackgroundLayout.setVerticalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlFormaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(pnlDadosCartao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(pnlBotao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        MenuCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/new.png"))); // NOI18N
        MenuCadastro.setText("Cadastro");

        cadastroCLiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cliente.png"))); // NOI18N
        cadastroCLiente.setText("Cadastro de Cliente");
        MenuCadastro.add(cadastroCLiente);

        cadastroFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/funcionario.png"))); // NOI18N
        cadastroFuncionario.setText("Cadastro de Funcionario");
        MenuCadastro.add(cadastroFuncionario);

        menuBar.add(MenuCadastro);

        MenuManutencao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/settings.png"))); // NOI18N
        MenuManutencao.setText("Manutenção");

        gerenciarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/alterclient.png"))); // NOI18N
        gerenciarCliente.setText("Gerenciar Clientes");
        gerenciarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerenciarClienteActionPerformed(evt);
            }
        });
        MenuManutencao.add(gerenciarCliente);

        gerenciarFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/funcionario.png"))); // NOI18N
        gerenciarFuncionario.setText("Gerenciar Funcionários");
        MenuManutencao.add(gerenciarFuncionario);

        menuBar.add(MenuManutencao);

        MenuAreaVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/sale.png"))); // NOI18N
        MenuAreaVenda.setText("Área de Vendas");

        Produtos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/bag.png"))); // NOI18N
        Produtos.setText("Produtos");
        MenuAreaVenda.add(Produtos);

        Carrinho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/buy.png"))); // NOI18N
        Carrinho.setText("Carrinho de Compras");
        MenuAreaVenda.add(Carrinho);

        menuBar.add(MenuAreaVenda);

        MenuLog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/log.png"))); // NOI18N
        MenuLog.setText("Relatório");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/logsintetic.png"))); // NOI18N
        jMenuItem1.setText("Relatório Sintético");
        MenuLog.add(jMenuItem1);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/lolanalitic.png"))); // NOI18N
        jMenuItem2.setText("Relatório Analítico");
        MenuLog.add(jMenuItem2);

        menuBar.add(MenuLog);

        MenuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/out.png"))); // NOI18N
        MenuSair.setText("Sair");
        menuBar.add(MenuSair);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gerenciarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerenciarClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gerenciarClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Venda_Forma_Pagamento_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Venda_Forma_Pagamento_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Venda_Forma_Pagamento_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Venda_Forma_Pagamento_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Venda_Forma_Pagamento_View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Carrinho;
    private javax.swing.JMenu MenuAreaVenda;
    private javax.swing.JMenu MenuCadastro;
    private javax.swing.JMenu MenuLog;
    private javax.swing.JMenu MenuManutencao;
    private javax.swing.JMenu MenuSair;
    private javax.swing.JMenuItem Produtos;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnComprar;
    private javax.swing.JMenuItem cadastroCLiente;
    private javax.swing.JMenuItem cadastroFuncionario;
    private javax.swing.JMenuItem gerenciarCliente;
    private javax.swing.JMenuItem gerenciarFuncionario;
    private javax.swing.ButtonGroup gpbBandeira;
    private javax.swing.ButtonGroup gpbFormaPagamento;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JLabel lblBandeira;
    private javax.swing.JLabel lblCVV;
    private javax.swing.JLabel lblDataValidade;
    private javax.swing.JLabel lblNomeCartao;
    private javax.swing.JLabel lblNumeroCartao;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JFormattedTextField mskCVV;
    private javax.swing.JFormattedTextField mskNumeroCartao;
    private javax.swing.JPanel pnlBackground;
    private javax.swing.JPanel pnlBotao;
    private javax.swing.JPanel pnlDadosCartao;
    private javax.swing.JPanel pnlFormaPagamento;
    private javax.swing.JRadioButton rdbBoleto;
    private javax.swing.JRadioButton rdbCredito;
    private javax.swing.JRadioButton rdbDebito;
    private javax.swing.JRadioButton rdbElo;
    private javax.swing.JRadioButton rdbMastercard;
    private javax.swing.JRadioButton rdbVisa;
    private javax.swing.JTextField txtNomeCartao;
    // End of variables declaration//GEN-END:variables
}
